# Site
name: "LJT"
title: "LJT"
description: "这里是李佳彤的个人主页，你可以在这里看到关于我的创作"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/lookswhite.github.io'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: xiahan@cuc.edu.cn

# Authors
authors:
  sal:
    name: LJT
    display_name: LJT
    avatar: 'assets/images/LJT.jpg'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    # email: wowthemesnet@gmail.com
    # web: https://www.wowthemes.net/donate/
    # twitter: https://twitter.com/wowthemesnet
    # description: "."
  john:
    name: enhui
    display_name: enhui
    avatar: 'assets/images/enhui.jpg'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    # email: wowthemesnet@gmail.com
    # web: https://www.wowthemes.net
    # twitter: https://twitter.com/wowthemesnet
    # description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
